# Site
title: Anna Foldberg
url: "https://annafoldberg.github.io"
baseurl: "/portfolio"
#show_downloads: false

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
search: true # built-in search
sass:
  sourcemap: never # disables sourcemaps

# Languages
languages: ["en","da","it"]
default_lang: "en"
exclude_from_localization: ["assets","images","favicon.ico"] # keeps assets, images, and favicons global instead of language-scoped

# Plugins
plugins:
  - jekyll-polyglot # needs GitHub Actions build
  - jekyll-include-cache
  - jekyll-archives # auto-generates archive pages by year/tag/category
  
# Permalinks
permalink: /:categories/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  notes:
    output: true
    permalink: /notes/:path/
  log:
    output: true
    permalink: /log/:path/

# Defaults for front matter
defaults:
  - scope:
      path: ""
    values:
      lang: en
  # Projects (Trackunit + mini projects)
  - scope:
      path: ""
      type: "projects"
    values:
      layout: collection
      toc: true
      sidebar: true
      classes: wide
  # Notes
  - scope:
      path: ""
      type: "notes"
    values:
      layout: categories
      toc: true
      sidebar: true
      classes: wide
  # Log
  - scope:
      path: ""
      type: "log"
    values:
      layout: page
      toc: true
      sidebar: true

# NOTE: Each page or post not in English must have a 'lang' key in its front matter

# Header/footer options
breadcrumbs: true
